.TH "IGNUIT" "1" "February 27th, 2012" "" ""
.\"
.\"
.\"
.SH "NAME"
ignuit - a flashcard-based memorization aid
.\"
.\"
.\"
.SH "SYNOPSIS"
\fBignuit\fR [\fBFILENAME\fR]
.\"
.\"
.\"
.SH "DESCRIPTION"
.PP
Ignuit is a memorization aid based on the Leitner flashcard system.
The program can be used for both long-term and short-term learning.
A complete user guide is available via the GNOME Help system.
.\"
.\"
.\"
.SH "OPTIONS"
.PP
If the name of a flashcard file is given when \fBignuit\fR is invoked, the
program will open that file.
.PP
Besides the standard GTK and GNOME options such as \fB\-\-help\fR and
\fB\-\-version\fR, ignuit has no commandline options of its own.
.\"
.\"
.\"
.SH "BUGS"
.PP
If you find a bug in the most recent version of ignuit, please email
the author.
.\"
.\"
.\"
.SH "AUTHORS"
.PP
Timothy Musson <trmusson@gmail.com>
.\"
.\"
.\"
.SH "COPYRIGHT NOTICE"
Copyright \(co 2012 Timothy Richard Musson
.PP
Copying and distribution of this file, with or without modification, are
permitted provided the copyright notice and this notice are preserved.

